<?php

namespace Chs\Messages\Entity\Faker;

use Faker\Provider\Base;

class Chs extends Base {

    protected $municipalities = [
        'acton.ma.us',
        'adams.ma.us',
        'adamsfire.ma.us',
        'ashland.ma.us',
        'billerica.ma.us',
        'blackstone.ma.us',
        'bolton.ma.us',
        'boxborough.ma.us',
        'boxford.ma.us',
        'brockton.ma.us',
        'buzzardsbay.ma.us',
        'chatham.ma.us',
        'chelmsford.ma.us',
        'chelmsfordwater.ma.us',
        'chelsea.ma.us',
        'chilmark.ma.us',
        'clinton.ma.us',
        'demo.ma.us',
        'dev.ma.us',
        'dighton.ma.us',
        'dracut.ma.us',
        'duxbury.ma.us',
        'eastham.ma.us',
        'eastlongmeadow.ma.us',
        'easton.ma.us',
        'essex.ma.us',
        'essexfd.ma.us',
        'everett.ma.us',
        'fairhaven.ma.us',
        'fitchburg.ma.us',
        'framingham.ma.us',
        'groton.ma.us',
        'groveland.ma.us',
        'hamilton.ma.us',
        'haverhill.ma.us',
        'holyoke.ma.us',
        'hudson.ma.us',
        'ipswich.ma.us',
        'kingston.ma.us',
        'lawrence.ma.us',
        'lincoln.ma.us',
        'lynn.ma.us',
        'malden.ma.us',
        'manchester.ma.us',
        'mansfield.ma.us',
        'marblehead.ma.us',
        'marshfield.ma.us',
        'maynard.ma.us',
        'medford.ma.us',
        'melrose.ma.us',
        'mendon.ma.us',
        'methuen.ma.us',
        'middleton.ma.us',
        'millbury.ma.us',
        'nahant.ma.us',
        'nantucket.ma.us',
        'newbedford.ma.us',
        'newbury.ma.us',
        'newton.ma.us',
        'norton.ma.us',
        'oxford.ma.us',
        'paxton.ma.us',
        'pembroke.ma.us',
        'pepperell.ma.us',
        'plainville.ma.us',
        'plymouth.ma.us',
        'randolph.ma.us',
        'revere.ma.us',
        'rockport.ma.us',
        'rowley.ma.us',
        'salem.ma.us',
        'salisbury.ma.us',
        'sharon.ma.us',
        'sherborn.ma.us',
        'shirley.ma.us',
        'shrewsbury.ma.us',
        'somerville.ma.us',
        'southborough.ma.us',
        'southhadley.ma.us',
        'springfield.ma.us',
        'stoughton.ma.us',
        'stow.ma.us',
        'sudbury.ma.us',
        'sutton.ma.us',
        'swampscott.ma.us',
        'taunton.ma.us',
        'tewksbury.ma.us',
        'topsfield.ma.us',
        'townsend.ma.us',
        'truro.ma.us',
        'uxbridge.ma.us',
        'waltham.ma.us',
        'wareham.ma.us',
        'watertown.ma.us',
        'wayland.ma.us',
        'webster.ma.us',
        'wellfleet.ma.us',
        'wenham.ma.us',
        'westborough.ma.us',
        'westboylston.ma.us',
        'westford.ma.us',
        'westnewbury.ma.us',
        'weston.ma.us',
        'westport.ma.us',
        'westtisbury.ma.us',
        'winthrop.ma.us',
        'worcester.ma.us',
        'yarmouth.ma.us',
        'oldsaybrook.ct.us',
        'kittery.me.us',
        'mountarlington.nj.us',
        'easton.pa.us',
        'reading.pa.us',
        'wilkesbarre.pa.us',
        'providence.ri.us',
        'brandon.vt.us',
    ];

    protected $systems = [
        'egov',
        'k2'
    ];

    public function municipalityCode(): string {
        return self::randomElement($this->municipalities);
    }

    public function system(): string {
        return self::randomElement($this->systems);
    }

}